// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBF_Cr7HCQfbNjn9I3yHU2SO2UkCm3C0',
    appId: '1:448224856968:web:69bf789cbade1b1c2fc83d',
    messagingSenderId: '448224856968',
    projectId: 'dream-smartlive',
    authDomain: 'dream-smartlive.firebaseapp.com',
    databaseURL: 'https://dream-smartlive-default-rtdb.firebaseio.com',
    storageBucket: 'dream-smartlive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKtP5WeHVKwUdOJkdX5_Eef6FAgoolJss',
    appId: '1:448224856968:android:f97a6307734458462fc83d',
    messagingSenderId: '448224856968',
    projectId: 'dream-smartlive',
    databaseURL: 'https://dream-smartlive-default-rtdb.firebaseio.com',
    storageBucket: 'dream-smartlive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbklSRO7A96WYvuWzYANXC6069mhwvnFo',
    appId: '1:448224856968:ios:b7ff86d65eb88ff92fc83d',
    messagingSenderId: '448224856968',
    projectId: 'dream-smartlive',
    databaseURL: 'https://dream-smartlive-default-rtdb.firebaseio.com',
    storageBucket: 'dream-smartlive.appspot.com',
    androidClientId: '448224856968-qlqcogol8btmi9igf3rim1sssgkq7k83.apps.googleusercontent.com',
    iosClientId: '448224856968-e9sm48icrj5uv1ha16vogkdnb4b9q745.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.smartlive',
  );
}
